### ISSUE TITLE
AbuseIPDB - IP Adressen regelmäßig löschen? =true verursacht Fatal Error

### ISSUE THREAD

**Issue by webconcept-one** [zencartpro/157-modul-abuseipdb#1]
PHP 8.2

```
[12-Nov-2024 13:36:03 Europe/Berlin] PHP Fatal error: Uncaught TypeError: zcDate::output(): Argument #1 ($format) must be of type string, null given, called in /includes/classes/observers/class.abuseipdb_observer.php on line 35 and defined in /includes/classes/zcDate.php:152
Stack trace:
#0 /includes/classes/observers/class.abuseipdb_observer.php(35): zcDate->output()
#1 /includes/classes/observers/class.abuseipdb_observer.php(20): abuseipdb_observer->runCleanup()
#2 /includes/classes/traits/NotifierManager.php(87): abuseipdb_observer->update()
#3 /includes/templates/responsive_classic/common/html_header.php(17): base->notify()
#4 /index.php(43): require('...')
#5 {main}
thrown in /includes/classes/zcDate.php on line 152
```

**Comment by webchills** [comment]
Kannst Du bitte mal auf Version 2.1.3 aktualisieren (noch nicht released, einfach aktuellen Stand mit dem Code Button herunterladen). Kann das mit der neuen Version nicht nachvollziehen. Bitte dann um Info, ob das mit 2.1.3 noch immer auftritt.
